service: Sylor

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - .venv/**
    - venv/
    - testing/
#    - .serverless/

custom:
  dynamodb:
    start:
      migrate: false # auto migrate on dynamodb start

provider:
#  s3:
#    imgBucket:
#      name: my-custom-bucket-name

  name: aws
  versionFunctions: false
  runtime: python3.9
  region: eu-central-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorUsersTable", "Arn" ] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorTranslations", "Arn" ] }
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorProducts", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorProductCategorySchema", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorProductSpecifics", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorProductGeneralSpecs", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorClients", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorOffers", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorOffersProduct", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorExtraCostings", "Arn" ] }

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "sylorOfferCostings", "Arn" ] }

functions:
#  resize:
#    handler: resize.handler
#    events:
#      - s3: imgBucket

  login_be:
    handler: authenticate/user_login.loging_request_receiver
    timeout: 29
    events:
      - httpApi:
          method: 'POST'
          path: /login

  user_management:
    handler: endpoints/users.user_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /users
      - httpApi:
          method: 'GET'
          path: /users/username
      - httpApi:
          method: 'POST'
          path: /users/signup
      - httpApi:
          method: 'DELETE'
          path: /users/delete
      - httpApi:
          method: 'PUT'
          path: /users/edit

  translations_management:
    handler: endpoints/translations_management/translations.translations_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /translations
      - httpApi:
          method: 'GET'
          path: /translations/id
      - httpApi:
          method: 'GET'
          path: /translations/type
      - httpApi:
          method: 'POST'
          path: /translations/registration
      - httpApi:
          method: 'DELETE'
          path: /translations/delete
      - httpApi:
          method: 'PUT'
          path: /translations/edit

  products_management:
    handler: endpoints/product_management/products.product_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /products
      - httpApi:
          method: 'GET'
          path: /products/id
      - httpApi:
          method: 'POST'
          path: /products/registration
      - httpApi:
          method: 'DELETE'
          path: /products/delete
      - httpApi:
          method: 'PUT'
          path: /products/edit
      - httpApi:
          method: 'PUT'
          path: /products/edit/img

  product_schema_management:
    handler: endpoints/product_management/product_category_schema.product_schema_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /product_schema
      - httpApi:
          method: 'GET'
          path: /product_schema/id
      - httpApi:
          method: 'POST'
          path: /product_schema/registration
      - httpApi:
          method: 'DELETE'
          path: /product_schema/delete
      - httpApi:
          method: 'PUT'
          path: /product_schema/edit

  clients_management:
    handler: endpoints/clients_management/clients.client_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /clients
      - httpApi:
          method: 'GET'
          path: /clients/id
      - httpApi:
          method: 'POST'
          path: /clients/registration
      - httpApi:
          method: 'DELETE'
          path: /clients/delete
      - httpApi:
          method: 'PUT'
          path: /clients/edit

  offers_management:
    handler: endpoints/offers_management/offers.offer_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /offers
      - httpApi:
          method: 'GET'
          path: /offers/id
      - httpApi:
          method: 'POST'
          path: /offers/registration
      - httpApi:
          method: 'DELETE'
          path: /offers/delete
      - httpApi:
          method: 'PUT'
          path: /offers/edit

  offers_product_management:
    handler: endpoints/offers_product_management/offers_product.offers_product_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /offers_product
      - httpApi:
          method: 'GET'
          path: /offers_product/id
      - httpApi:
          method: 'POST'
          path: /offers_product/registration
      - httpApi:
          method: 'DELETE'
          path: /offers_product/delete
      - httpApi:
          method: 'PUT'
          path: /offers_product/edit

  extra_costings_management:
    handler: endpoints/extra_costings_management/extra_costings.extra_costings_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /extra_costings
      - httpApi:
          method: 'GET'
          path: /extra_costings/id
      - httpApi:
          method: 'GET'
          path: /extra_costings/typologyId
      - httpApi:
          method: 'POST'
          path: /extra_costings/registration
      - httpApi:
          method: 'DELETE'
          path: /extra_costings/delete
      - httpApi:
          method: 'PUT'
          path: /extra_costings/edit

  costing_management:
    handler: endpoints/costing/costing.costing_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /costing
      - httpApi:
          method: 'POST'
          path: /costing/registration

  offer_costing_management:
    handler: endpoints/offer_costing/offer_costing.offer_costing_related_methods
    timeout: 29
    events:
      - httpApi:
          method: 'GET'
          path: /offer_costing/id
      - httpApi:
          method: 'GET'
          path: /offer_costing/offer_id
      - httpApi:
          method: 'POST'
          path: /offer_costing/registration
      - httpApi:
          method: 'PUT'
          path: /offer_costing/edit
#      - httpApi:
#          method: 'DELETE'
#          path: /offer_costing/delete

resources:
  Resources:
    SylorImgBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sylorimgbucket
        AccessControl: PublicRead

    sylorOfferCostings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorOfferCostings
        AttributeDefinitions:
          - AttributeName: offer_costing_id
            AttributeType: S
        KeySchema:
          - AttributeName: offer_costing_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorExtraCostings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorExtraCostings
        AttributeDefinitions:
          - AttributeName: extra_costing_id
            AttributeType: S
        KeySchema:
          - AttributeName: extra_costing_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorUsersTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorTranslations:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorTranslations
        AttributeDefinitions:
          - AttributeName: translation_id
            AttributeType: S
        KeySchema:
          - AttributeName: translation_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorProductSpecifics:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorProductSpecifics
        AttributeDefinitions:
          - AttributeName: specifics_key
            AttributeType: S
        KeySchema:
          - AttributeName: specifics_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorProductCategorySchema:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorProductCategorySchema
        AttributeDefinitions:
          - AttributeName: schemas_key
            AttributeType: S
        KeySchema:
          - AttributeName: schemas_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorProductGeneralSpecs:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorProductGeneralSpecs
        AttributeDefinitions:
          - AttributeName: general_spec_key
            AttributeType: S
        KeySchema:
          - AttributeName: general_spec_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorProducts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorProducts
        AttributeDefinitions:
          - AttributeName: product_key
            AttributeType: S
        KeySchema:
          - AttributeName: product_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorClients:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorClients
        AttributeDefinitions:
          - AttributeName: client_key
            AttributeType: S
        KeySchema:
          - AttributeName: client_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorOffers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorOffers
        AttributeDefinitions:
          - AttributeName: offer_key
            AttributeType: S
        KeySchema:
          - AttributeName: offer_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sylorOffersProduct:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sylorOffersProduct
        AttributeDefinitions:
          - AttributeName: offer_product_key
            AttributeType: S
        KeySchema:
          - AttributeName: offer_product_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

